services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spring_security
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
       - 'backend'
  redis:
    image: redis:7
    container_name: my_redis
    ports:
      - "6377:6379"
    volumes:
      - 'redis-data:/data'
    restart: always
    command: redis-server --appendonly yes
    networks:
      - 'backend'
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    networks:
      - 'backend'
volumes:
  postgres_data:
  redis-data:

networks:
  backend:
